//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "locations")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: String,
    pub is_east: bool,
    pub longitude_degree: u16,
    pub longitude_minute: u8,
    pub longitude_second: u8,
    pub is_north: bool,
    pub latitude_degree: u8,
    pub latitude_minute: u8,
    pub latitude_second: u8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::horoscopes::Entity")]
    Horoscopes,
}

impl Related<super::horoscopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Horoscopes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
