//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub name: String,
    pub password: String,
    pub salt: String,
    pub create_date: DateTime,
    pub last_login_date: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::native::Entity")]
    Native,
}

impl Related<super::native::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Native.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
