//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub username: String,
    pub password_hash: String,
    pub salt: String,
    pub created_at: DateTime,
    pub last_login_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::horoscopes::Entity")]
    Horoscopes,
}

impl Related<super::horoscopes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Horoscopes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
